const path = require('path');
const fs = require('fs');

// Hostinger Standalone Launcher
// This file is the entry point configured in Hostinger's Node.js settings.
// It launches the Next.js standalone server generated by `next build`.

process.env.PORT = process.env.PORT || '3000';
process.env.HOSTNAME = process.env.HOSTNAME || '0.0.0.0';

const standaloneServer = path.join(__dirname, '.next', 'standalone', 'server.js');

if (fs.existsSync(standaloneServer)) {
  console.log('🚀 Nutrexia: Launching Next.js standalone server...');
  require(standaloneServer);
} else {
  console.error('❌ Nutrexia: .next/standalone/server.js not found.');
  console.error('   Run "npm run build" first to generate the standalone output.');
  process.exit(1);
}
